CAPE now outputs Labels in CSV format
MobileRoboticsSkoltech/point-cloud-plane-extraction pull request #28
Opened 2022-07-22 18:08 UTC by true-real-michael

Image saving is still possible via `--save-img` flag.

Used templates in `writeLabelsTable` because I also use this function for outputting other matrices when debugging.

This branch was based on the branch with INI file reading, that's why changes about reading INI file are also here.

2022-07-22 19:19 UTC, DmiitriyJarosh requested changes

2022-07-22 19:19 UTC, DmiitriyJarosh commented on CAPE/CAPE/CMakeLists.txt
> +	Params.cpp write_labels.hpp)
а почему hpp? и он почему на этой строке?

2022-07-22 19:19 UTC, DmiitriyJarosh commented on CAPE/CAPE/run_cape_offline.cpp
> +        input_path << "input";
вот это не ломает докер?

2022-07-22 19:19 UTC, DmiitriyJarosh commented on CAPE/CAPE/run_cape_offline.cpp
> +    calib_path << input_path.str() << "/calib_params.xml";
а вот эти параметры еще ведь нужны? что в них? мы подаем не облако для алгоса?

2022-07-22 19:19 UTC, DmiitriyJarosh commented on CAPE/CAPE/write_labels.hpp
> +            fout << +*sCode << ',';
стращно спросить что делает `+`

2022-07-22 19:19 UTC, DmiitriyJarosh commented on CAPE/CAPE/write_labels.hpp
> +        sCode = data.template ptr<T>(r);
вообще эти все темплейты обязательны? какая у них цель?

2022-07-23 09:46 UTC, true-real-michael commented on CAPE/CAPE/run_cape_offline.cpp
> +    calib_path << input_path.str() << "/calib_params.xml";
Там intrinsics камеры
CAPE принимает .png и по нему строит облако, поэтому этот файл нужен

2022-07-23 09:47 UTC, true-real-michael commented on CAPE/CAPE/write_labels.hpp
> +            fout << +*sCode << ',';
`*sCode` имеет произвольный тип, а `+` заставляет его выводиться как число.
Поменяю это на `static_cast` для читабельности

2022-07-23 11:13 UTC, true-real-michael commented on CAPE/CAPE/write_labels.hpp
> +        sCode = data.template ptr<T>(r);
Я их использовал для дебага (использовал эту функцию для вывода матриц c разными типами). Для самого алгоритма они не обязательны

2022-07-31 11:12 UTC, merged